
package gui;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DateFormat;
import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import model.Reservation;
import model.User;

/**
 *
 * @author usuario
 */
public class ReservationForm extends javax.swing.JFrame {
    
    public Reservation reservation;
    public User user;
    
    public ReservationForm(User user, Reservation reservation) {
        initComponents();
        this.user = user;
        this.reservation = null;
        
        //set data in list
        refreshList();
        
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }

    
    private void refreshList() {
        
        if (!user.getReservationHistory().isEmpty()) {
            DefaultListModel lM;
            lM = new DefaultListModel();
        
        for (Reservation r: user.getReservationHistory()) {
            lM.addElement(r);
        }
        lstReservationHistory.setModel(lM);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        lblDateIn = new javax.swing.JLabel();
        lblDateOut = new javax.swing.JLabel();
        txtDateIn = new javax.swing.JTextField();
        txtDateOut = new javax.swing.JTextField();
        btnModify = new javax.swing.JButton();
        lblLodgementName = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        lblTotalPrice = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstReservationHistory = new javax.swing.JList<>();
        lblMessage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDateIn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDateIn.setText("Fecha de llegada:");

        lblDateOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDateOut.setText("Fecha de salida:");

        btnModify.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModify.setText("Modificar");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        lblLodgementName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLodgementName.setText("Propiedad");

        txtTotalPrice.setEditable(false);

        lblTotalPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalPrice.setText("Precio Total:");

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(lblTotalPrice)
                                .addGap(26, 26, 26)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel2Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(lblLodgementName))))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDateOut)
                                    .addComponent(lblDateIn))
                                .addGap(26, 26, 26)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDateIn)
                                    .addComponent(txtDateOut, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnModify)
                        .addGap(61, 61, 61)
                        .addComponent(btnCancel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLodgementName)
                .addGap(33, 33, 33)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateIn)
                    .addComponent(txtDateIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDateOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateOut))
                .addGap(47, 47, 47)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPrice))
                .addGap(36, 36, 36)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModify)
                    .addComponent(btnCancel))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        lstReservationHistory.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "No hay reservas" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstReservationHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstReservationHistoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstReservationHistory);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("BNB");
        jLabel2.setPreferredSize(new java.awt.Dimension(907, 622));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        lblMessage.setText("");
        if (reservation == null) {
            return;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        Date dateIn = sdf.parse(txtDateIn.getText(), new ParsePosition(0));
        if(null == dateIn) {        
            lblMessage.setText("Fecha de llegada no válida.");
            return;
        } 


        Date dateOut = sdf.parse(txtDateOut.getText(), new ParsePosition(0));
        
        if(dateOut == null){
            lblMessage.setText("Fecha de salida no válida.");
            return;
        }
        
        double totalPrice = Reservation.getTotalPrice(reservation.getLodgement(), dateIn, dateOut);
        
        if (totalPrice <= 0) {
            lblMessage.setText("Introduzca fechas válidas");
            return;
        }

        txtTotalPrice.setText(totalPrice + " €");
        
        if (reservation.modifyReservation( dateIn, dateOut)) {
            lblMessage.setText("La reserva ha sido modificada");
            
            refreshList();
            
        } else {
            lblMessage.setText("No es posible realizar la modificación porque ya está pagada");
        }
        
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        
        if (reservation == null) {
            return;
        }
        reservation.cancelReservation();
        
        refreshList();
        
        lblMessage.setText("La reserva ha sido cancelada");
    }//GEN-LAST:event_btnCancelActionPerformed

    private void lstReservationHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstReservationHistoryMouseClicked
        // TODO add your handling code here:
        lstReservationHistory.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent me) {
                JList target = (JList)me.getSource();
                int index = target.locationToIndex(me.getPoint());
                if (index >= 0) {
                    Object item = target.getModel().getElementAt(index);
                    //Set information from selected lodgement

                    reservation = (Reservation) item;
                    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yy");
                    String strDate = dateFormat.format(reservation.getDateIn());
                    txtDateIn.setText(strDate);
                    strDate = dateFormat.format(reservation.getDateOut());
                    txtDateOut.setText(strDate);
                    double totalPrice = Reservation.getTotalPrice(reservation.getLodgement(), reservation.getDateOut(), reservation.getDateOut());
                    txtTotalPrice.setText(totalPrice + " €");
                    lblLodgementName.setText(reservation.getLodgement().getName());
                }
            }
        });
        
    }//GEN-LAST:event_lstReservationHistoryMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnModify;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDateIn;
    private javax.swing.JLabel lblDateOut;
    private javax.swing.JLabel lblLodgementName;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JList<String> lstReservationHistory;
    private java.awt.Panel panel2;
    private javax.swing.JTextField txtDateIn;
    private javax.swing.JTextField txtDateOut;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables
}
